### PR TITLE
Move tests to Github Actions

### PR DESCRIPTION
**Pull request by cheesema**
Starting to try and use gihub actions

### CODE REVIEW

**Comment by cheesema** [comment]
Things are working, but windows tests seem way to slow. Something is wrong. Maybe it is running a debug build?

**Comment by cheesema** [comment]
Almost there.. just need to get OpenMP working on OSX, and confirm that OpenMP is actually runnign in windows, as the tests take the same time as osx which seems to indicate not.

**Comment by cheesema** [comment]
Would like to get this through to develop, and then to master. 

Tests now with github actions, travis removed.

Upside:
-build process is now all using vcpkg across platform (with exception of some flags for blosc which is per distributions).
-waayy faster (3-5 times)
-free

**Review by joeljonsson — APPROVED** [review]
great job!

**Pull request merged**
