### PR TITLE
Windows compile

### PR DESCRIPTION
**Pull request by cheesema**
Using vcpkg x64-windows tool chain and MSCV 16.8.6 have a working build with Clang and OpenMP. Still working out some kinks with optimisation flags, and MSVC stopped working with the recent updates, but there is no OpenMP support there anyway. 

Still quite a few things to test, creating install instructures, and replicating. But positive signs!

Platform | Static | Shared
-- | -- | --
Linux GCC | internal blosc error | Yes
Windows MSCV (>=16.8.6) |Yes(no openmp)  | Yes (No openmp)
Windows Clang(>=16.8.6) | Yes (vcpkg x64-windows) | Yes (vcpkg x64-windows)

**Main change for OpenMP:**

1.) Seems to be the fact that linking openMP with the flags directly didn't seem to work, but instead using target_link_libraries with the OpenMP linking as bleow does seem to work. 

target_link_libraries(${STATIC_TARGET_NAME}  OpenMP::OpenMP_CXX  )

2.) This seems to only work since MSCV Clang released with 16.8.6

Consequencies:

This seems to open up a complete install using vcpkg, could also create a port then for vcppkg installation. 

Still to do:

- [x] Windows compile on travis.
- [x] Install instructions for Windows using choclatey and without. 
- [x] Getting lib install instructions working for Windows.

### CODE REVIEW

**Comment by cheesema** [comment]
@joeljonsson when you have the time are you able to give this a go following the install instructions in the README?

**Review by joeljonsson — DISMISSED** [review]
Edit: building according to the instructions using choco/clangcl works, but OpenMP is not found. Will try to look into this further tomorrow

**Comment by cheesema** [comment]
We still have the crash issues with windows from the CL for 2 of the tests right @joeljonsson ?

**Comment by joeljonsson** [comment]
Removing the nested openmp pragmas seems to have done the trick. I can now run the tests and benchmarks from the command line without issues.

**Comment by cheesema** [comment]
@joeljonsson check the debug flags in windows work for you outside of gtest.

Have a look at the update instructions and suggest any changes.

**Comment by cheesema** [comment]
So I will need to update the windows install instructions as you do need to install llvm it seems. Outside of that and the merge in @joeljonsson did you mention there was something else failing that I should update before we merge?

**Comment by cheesema** [comment]
- [ ] Update install instructions to install llvm (... not sure what else is missing, this feels like a band-aid).
- [ ] Push a bit further to see for clang-cl in debug mode on windows (currently seg faults for tests, and for Example_get_apr, on hdf5 step) Seems to be a clue there. I think it may have something to do with vcpkg install route.

**Comment by cheesema** [comment]
@joeljonsson I believe I have addressed the remaining issues. Brew has fallen over for some reason so the OSX build is failing, as in the Pylibapr build.

I would suggest you try your previous failure cases? The debug mode should now be working (Needed to update one flag), then approve this.

**Comment by cheesema** [comment]
- [ ]  Static build with internal blosc is failing to build.

**Comment by cheesema** [comment]
@cheesema
Fix reference input to function for allocation of object
d7d70bc For @joeljonsson

**Comment by joeljonsson** [comment]
> * [ ]   Static build with internal blosc is failing to build.

This should be fixed now. But we may still want to consider simply removing blosc from submodules

**Review by joeljonsson — APPROVED** [review]
This is good to go from my side.

There still seems to be an issue building the shared library on windows, but the default settings (static on, shared off) work fine for me on windows, osx and ubuntu.

**Pull request merged**
