### PR TITLE
update file I/O

### PR DESCRIPTION
**Pull request by joeljonsson**
plan to add some useful things to the io here, such as type detection for particle datasets.

### CODE REVIEW

**Comment by cheesema** [comment]
Cool is this in the direction of enabling auto read detection through python?

**Comment by joeljonsson** [comment]
That's the idea! I'm sure there is a better way to do this, but for now I just implemented a method that opens the dataset, compares the type to the ones we support and returns the matching type as a string. In Python it's then easy to write a function that fetches the type this way and initializes/returns a `ParticleData` object of the appropriate type. Doing something similar in C++ is tricky though, since the type is not known at compile time.

**Review by cheesema — APPROVED** [review]

**Comment by cheesema** [comment]
Added some tests in and a slight re-factor to avoid some code duplication.

**Review by cheesema — APPROVED** [review]
Addition of tests, and all seems to be working + minor change to get osx working agian.

**Pull request merged**
